// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts            string
	IncidentActions     string
	Incidents           string
	MonitorCheckResults string
	Monitors            string
	Subscribers         string
	Users               string
}{
	Accounts:            "accounts",
	IncidentActions:     "incident_actions",
	Incidents:           "incidents",
	MonitorCheckResults: "monitor_check_results",
	Monitors:            "monitors",
	Subscribers:         "subscribers",
	Users:               "users",
}
