version: '3.9'

services:
  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./misc/tools/reflex
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVICE: service
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app

  endpoint_simulator:
    build: ./misc/tools/reflex
    environment:
      SERVICE: endpoint_simulator
    ports:
      - "8090:8090"
    volumes:
      - .:/usr/app
