# fly.toml app configuration file generated for dobermann on 2023-12-09T22:09:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prod-dobermann-worker"
primary_region = "lhr"

[build]
  dockerfile = "../../worker.Dockerfile"

[env]
  PRODUCTION_MODE=true
  ENDPOINT_CHECK_TIMEOUT_IN_SECONDS=30

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
