// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accounts              string
	AlertTriggers         string
	MonitorAlertTriggers  string
	MonitorCheckResults   string
	MonitorRegions        string
	MonitorRequestHeaders string
	Monitors              string
	Regions               string
	TeamMembers           string
	Teams                 string
	Users                 string
}{
	Accounts:              "accounts",
	AlertTriggers:         "alert_triggers",
	MonitorAlertTriggers:  "monitor_alert_triggers",
	MonitorCheckResults:   "monitor_check_results",
	MonitorRegions:        "monitor_regions",
	MonitorRequestHeaders: "monitor_request_headers",
	Monitors:              "monitors",
	Regions:               "regions",
	TeamMembers:           "team_members",
	Teams:                 "teams",
	Users:                 "users",
}
