name: backend-main
on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backend-*.yml"

jobs:
  ci:
    uses: ./.github/workflows/backend-ci.yml

  tag:
    uses: ./.github/workflows/tag.yml
    needs: ci
    secrets:
      PAT: ${{ secrets.PAT }}
